### ISSUE TITLE
Problem with Auth0

### ISSUE THREAD

**Issue by fabiojansenbr** [AKouki/AspNetCore-ITrackerSPA#1]
Hi, i want to test this app. How i can configure Auth0 to work with? I created an api on auth0 website, but i just received a Domain like xxxx.auth0.com

I tried to put the domain on:

  "Auth0": {
    "Domain": "xxxx.auth0.com",
    "ApiIdentifier": "xxxx.auth0.com"
  }

But the app dont run. When i try to login, i receive this error: Something went wrong.
Please contact technical support.

Thanks

**Comment by AKouki** [comment]
Make sure  `Startup.cs -> Configure` contains the below code
```
var options = new JwtBearerOptions
{
    Audience = Configuration["Auth0:ApiIdentifier"],
    Authority = $"https://{Configuration["Auth0:Domain"]}/"
};

app.UseJwtBearerAuthentication(options);
```
Then go to Auth0 website and add/check your callback url `Clients - Settings - Allowed Callback URLs`. (You may need to change port)
```
http://localhost:5000
or
http://localhost:5000/home
```
